esphome:
  name: "m5coreink"

esp32:
  board: m5stack-coreink

wifi:
  ssid:     !secret wifi_ssid
  password: !secret wifi_pwd
  manual_ip:
    static_ip: 192.168.1.201
    gateway: 192.168.1.1
    subnet: 255.255.255.0

captive_portal:

logger:
  level: VERBOSE

api:
  password: !secret api_pwd

ota:
  password: !secret ota_pwd



binary_sensor:
  - platform: gpio
    name: press
    pin: GPIO38
    on_press:
      then:
        - logger.log: "press"
  - platform: gpio
    name: up
    pin: GPIO37
    on_press:
      then:
        - logger.log: "up"
  - platform: gpio
    name: down
    pin: GPIO39
    on_press:
      then:
        - logger.log: "down"


font:
  - file: 'fonts/28 Days Later.ttf'
    id: font1
    size: 30

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

display:
  - platform: waveshare_epaper
    id: my_display
    cs_pin: GPIO9
    dc_pin: GPIO15
    busy_pin:
      number: GPIO4
      inverted: true
    reset_pin: GPIO0
    model: 1.54in-m5coreink-m09
    update_interval: 8s
    lambda: |-
      it.print(5, 5, id(font1), "Timi a reussi!");
