substitutions:
  name: "seeedd1001screen"
  friendly_name: "Home Assistant Controller"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd

packages:
  setup:
    # url: https://github.com/lamiskin/espcontrol-community-devices/
    # ref: community-v0.4.1-upstream.v2.8.1
    # url: https://github.com/ibizaman/espcontrol-community-devices/
    url: file:///home/timi/Projects/espcontrol-community-devices/
    ref: main
    file: devices/seeed-esp32-p4-reterminal-d1001/packages.yaml
    refresh: 1s
